### ISSUE TITLE
Wallet Send Screen Meta Issue

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/ui-kit#102]
**Context**
The objective is to identify and develop all the components that need to be added to the ui-kit. 
![Screenshot from 2023-05-19 13-51-21](https://github.com/massalabs/ui-kit/assets/90157528/5ef1229a-ab55-48c1-bedc-32689e84fca6)

**How to**

- [x] Create a global (send & receive compatible component)  that will contain all of of the information that will be passed as a parameter in the Tabs component (this is a proposition  what do you think @mazmassa @maxime-carabina @Thykof )

- [x] Create Account Balance Component (To be defined)
![Screenshot from 2023-05-19 13-57-23](https://github.com/massalabs/ui-kit/assets/90157528/604a18ed-71aa-4b07-a8b1-b11c7d59591a)

- [x] Verify if the input and dropdown can be combined for this component
![Screenshot from 2023-05-19 14-35-53](https://github.com/massalabs/ui-kit/assets/90157528/a6a98efd-416a-4b8b-b664-64a9e5f6cf35)

- [x] Define the percentage components and how it works ( @SlnPons  @LucasF243  @mazmassa )
![Screenshot from 2023-05-19 14-37-43](https://github.com/massalabs/ui-kit/assets/90157528/6b1caf13-fc17-4841-866a-8073d5dd8998)

- [x] Verify if the input component can take in a icon which opens the contact list modal
![Screenshot from 2023-05-19 13-47-07](https://github.com/massalabs/ui-kit/assets/90157528/01b70920-42fc-4f2a-a23c-e8379a729a2f)

- [x] Verify that the popup modal component is compatible (take components as param) with contact list and account list components 

![Screenshot from 2023-05-19 13-55-56](https://github.com/massalabs/ui-kit/assets/90157528/a1a0db98-92c1-4432-a695-9be1ea3fe58c)

![Screenshot from 2023-05-19 13-55-03](https://github.com/massalabs/ui-kit/assets/90157528/fe8be16a-b0b1-45cc-9aae-eed1d5794839)

**Comment by SlnPons** [comment]
@pivilartisant Hey Paul, just saw this issue you created. It's great we have the list of tasks somewhere. But 2 comments:

1. The work described is not exactly correct. Simply because we'll break down the screen into different iterations to secure the basics first ;) 
Check [this page](https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=324-5834&t=ZtQNw8kA7DiXXTJ7-0) of the design, I added details and rules concerning this particular page.
Have a look and let's update this task together. 

2. All the rules are defined on the design. Have a look and let me know if it's clear.

**Comment by SlnPons** [comment]
@pivilartisant Hey Paul, just saw this issue you created. It's great we have the list of tasks somewhere. But 2 comments:

1. The work described is not exactly correct. Simply because we'll break down the screen into different iterations to secure the basics first ;) 
Check [this page](https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=324-5834&t=ZtQNw8kA7DiXXTJ7-0) of the design, I added details and rules concerning this particular page.
Have a look and let's update this task together. 

2. All the rules are defined on the design. Have a look and let me know if it's clear.
