### ISSUE TITLE
Add Sidemenu

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/ui-kit#18]
**Context**

- [ ] Create SideBar in the ui-kit 
Divide this into smaller components and smaller pr 
- [x] #19
- [ ] #22

For all of them : 
- [ ] Create Tests for Sidebar components
- [ ] Create Stories for Sidebar components

**How to**
Create components in the ui-kit 
Create Tests 
Create Stories

**Technical details**
Responsive and Sharp 

**QA testing**
Use Cypress if it's implemented
or 
Ask for a dev to create a component "Test" to test it in another project outside of the ui-kit

**Estimation**
5-6 days with tests and stuffs like that

**Comment by SlnPons** [comment]
@mazmassa this ticket has been done isn't it?

**Comment by mazmassa** [comment]
> @mazmassa this ticket has been done isn't it?

Sure!
